const REGISTER_FAIL = 'REGISTER_FAIL'
const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
const SUCCESS_MESSAGE_CLEAR = 'SUCCESS_MESSAGE_CLEAR'
const ERROR_CLEAR = 'ERROR_CLEAR'
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export {
    REGISTER_FAIL,REGISTER_SUCCESS,SUCCESS_MESSAGE_CLEAR,ERROR_CLEAR,USER_LOGIN_FAIL,USER_LOGIN_SUCCESS,LOGOUT_SUCCESS 
}